version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-petshop
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1122
    ports:
      - "6666:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
